name: supabase_db
description: A starting point for Dart libraries or applications.


environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  supabase_flutter: 1.10.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
