name: supado_api
description: The interface and models for an API providing access.

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4