name: project_list
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  projects_repository:
    path: ../../projects_repository
  supado_api:
    path: ../../supado_api
  supabase_flutter: ^1.10.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
