name: actions_repository
description: Action repository
publish_to: none

environment:
  sdk: ^3.0.2

dependencies:
  supabase_api:
    path: ../supabase_api
  domain_models:
    path: ../domain_models


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
